server:
  port: 8761

spring:
  application:
    name: EurekaServiceApplication

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    selfPreservation: true
  serviceUrl:
    defaultZone: http://localhost:8761


logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    com.furnituremanager: DEBUG
