eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

spring:
  application:
    name: configurationService
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
          uri: https://github.com/pattyt0/configsvr.git
          strictHostKeyChecking: false
